# Generated by Django 4.2.9 on 2024-02-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_part', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='input',
            new_name='inputs',
        ),
    ]
